# Generated by Django 5.1.6 on 2025-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('entgelt', models.IntegerField(verbose_name='Gehalt')),
                ('aktiv', models.BooleanField(verbose_name='Aktiv')),
                ('eintritt', models.DateField(verbose_name='Mitarbeiter seit')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
            },
        ),
    ]
